apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: app-tls
  namespace: fruits
  files:
    - "TLS/tls.crt"
    - "TLS/tls.key"
  type: "kubernetes.io/tls"
