apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fruits-library
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: fruitslib-frnt-tls
  namespace: fruits-library
  files:
    - "certificate/tls.crt"
    - "certificate/tls.key"
resources:
- frontend-apple.yaml
- frontend-banana.yaml